stages:
  - build

build_images:
  stage: build
  image: docker::20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t ninomunich/app-cicd:1.0 app/.
    - docker push ninomunich/app-cicd:1.0
  
    deploy_gcp:
      
      stage: deploy_gcp

      before_script:
        - chmod 400 $SSH_KEY
      
      script:
        - ssh -O StrictHostKeyChecking-no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -RF./app-cicd/ && sudo git clone git@gitlab.com:ninomunich/app-cicd.git && cd app-cicd && sudo chmod +x ./script.sh && sudo ./script.sh"
